spring:
    application:
        name: EchoProject
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: faith1918!
#    data:
#        redis:
#            host: localhost
#            port: 6379
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
server:
    port: 8080

#spring.application.name=EchoProject

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://database-2.c1y00w6gqa7k.ap-northeast-2.rds.amazonaws.com:3306/demo
#spring.datasource.url=jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=faith1918!

#server.port=8080
#Hibernate ddl ??
#create (db? ???)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#
#spring.jwt.secret=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
#server.ssl.key-store:keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=faith1918!
