name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 1. Java 21 설치
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    # 2. Gradle 권한 설정
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
        
    # 3. Gradle로 빌드
    - name: Build with Gradle
      uses: gradle/gradle-build-action@main
      with:
        arguments: build
        
    # 4. Docker 이미지 빌드 및 푸시
    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/echoproject:1.0.0 .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/echoproject:1.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/echoproject:1.0.0
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/echoproject:1.0.0
